name: 'Unanimously Approved'
description: 'Approved by all reviewers'
author: 'SnowCait'
inputs:
  token:
    required: true
    description: GitHub token
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-circle'
  color: 'green'
